export const environment = {
  production: true,
  settingsLocation: '/static/app-prd.json',
  platformName: 'Laundry Ladies LLC',
  platformNameShort: 'LL',
  serviceProviderName: 'Laundry Lady',
  serviceProviderNamePlural: 'Laundry Ladies',
  serviceAreas: ['Aleppo', 'Aspinwall', 'Avalon', 'Baldwin', 'Bellevue', 'Ben Avon', 'Bethel Park', 'Blawnox', 
    'Bradford Woods', 'Bridgeville', 'Carnegie', 'Castle Shannon', 'Cheswick', 'Churchill', 'Collier', 'Coraopolis', 
    'Crafton', 'Crescent', 'Dormont', 'East Deer', 'Edgeworth', 'Emsworth', 'Findlay', 'Fox Chapel', 'Franklin Park', 
    'Glen Osborne', 'Greentree', 'Hampton', 'Harmar', 'Haysville', 'Heidelberg', 'Ingram', 'Kennedy', 'Kilbuck', 'Leet', 
    'Leetsdale', 'Marshall', 'McCandless', 'McDonald', 'McKees Rocks', 'Monroeville', 'Moon', 'Mt. Lebanon', 'Neville', 
    'North Fayette', 'Oakdale', 'Oakmont', 'O’Hara', 'Ohio', 'Penn Hills', 'Pennsbury Village', 'Pine', 'Pittsburgh', 
    'Plum', 'Richland', 'Robinson', 'Ross', 'Rosslyn Farms', 'Scott', 'Sewickley', 'Shaler', 'Sharpsburg', 'South Fayette', 
    'Springsdale', 'Stowe', 'Thornburg', 'Upper St. Clair'],
  selectStaffEnabled: false,
  googleClientId: '668097874010-45pit3lc5uig78683v8hd1l4ulvq932a.apps.googleusercontent.com',
  staticImgPath: 'https://1297557073.rsc.cdn77.org/laundry/',
  termsUrl: 'https://1297557073.rsc.cdn77.org/laundry/sitedocs/terms.htm',
  privacyUrl: 'https://1297557073.rsc.cdn77.org/laundry/sitedocs/privacy.htm',
  faqUrl: 'https://1297557073.rsc.cdn77.org/laundry/sitedocs/faq.htm',
  stripePublicApiKey: 'pk_live_sGglkKWUDZ8ODipVBGCKcVpH',
  googleApiKey: 'AIzaSyCkUUe-D8acqN9y2D1CpWlhFf1AykFPWjE',
  fbAppId: '384020495352294',
  sentryAPIKey: 'https://cff3697d00c44e7a8ff49e5af49c7970@sentry.io/233435',
  fbSocialUrl: 'https://www.facebook.com/TheLaundyLadies/',
  showFbSocial: true,
  twitterSocialUrl: '',
  showTwitterSocial: false,
  linkedInSocialUrl: '',
  showLinkedInSocial: false,
  instagramSocialUrl: '',
  showInstagramSocial: false,
  appFavicon: 'laundryladies.ico',
  hailProfile: false,
  pickupProfile: false,
  enableTimeSelection: true,
};
